version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d) 
      - echo Compiling the Node.js code
      - npm run test
      - echo Creating build dir
      - npm run build
  post_build:
    commands:
      - echo Build completed on $(date +%Y-%m-%d)
  artifacts:
    files:
      - build/static/*